### PR TITLE
add notebooks overlay

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@b4mad.net>

### CODE REVIEW

**Comment by goern** [comment]
@harshad16 I'm doing a `/deploy` for an overlay build, the PipelineRun give:

```
conditions:
  - type: Succeeded
    status: 'False'
    lastTransitionTime: '2022-11-29T09:28:58Z'
    reason: CouldntGetTask
    message: >-
      failed to create task run pod
      "aicoe-pipelinerun-1312c574-1d2e-453c-8d0f-a17306526f8e-pr-vtvpb": Pod
      "aicoe-pipelinerun-1312c574-1d2e-453c-8d0f-a17306526f8e-pr-bm2km" is
      invalid: [spec.volumes[9].secret.secretName: Required value,
      spec.containers[7].volumeMounts[1].name: Not found: "quay-creds"]. Maybe
      missing or invalid Task opf-ci-pipelines/pr-build-release
```

see https://tekton.operate-first.cloud/#/namespaces/opf-ci-pipelines/pipelineruns/aicoe-pipelinerun-1312c574-1d2e-453c-8d0f-a17306526f8e?pipelineTask=pr-build-release-run&view=status

PS: can we incr the retention time for the PipelineRuns?

**Comment by goern** [comment]
is https://github.com/AICoE/aicoe-ci/blob/master/tasks/overlays-pipeline.yaml#L79 related? is there a `params.` missing?

**Comment by harshad16** [comment]
As this repository is set for overlay build, the simple `/deploy` will not work.
Use `/deploy <overlay-name>` : for example: `/deploy paddock`

if you would like build all overlays, please comment for each overlays separately in one separate single comment.

**Comment by goern** [comment]
> Additionally, no overlay for name notebooks found.

@harshad16 is this failing because aicoe-ci is looking at `.aicoe-ci.yaml` of the base branch rather then the PR itself?

**Comment by harshad16** [comment]
> > Additionally, no overlay for name notebooks found.
> 
>  is this failing because aicoe-ci is looking at `.aicoe-ci.yaml` of the base branch rather then the PR itself?

yes @goern , we do the check for existing overlay on the base (default) branch

**Pull request merged**
