### PR TITLE
add pre commit check

### PR DESCRIPTION
**Pull request by goern**
- ✨ 🆙 add phobos-test environment using sealedsecrets
- add pre-commit job
- reformatting via pre-commit

### CODE REVIEW

**Comment by durandom** [comment]
@goern I adjusted the existing pre-commit job at https://github.com/b4mad/racing/pull/267/commits/862117fa2b272a7ebd6f86659f38ed5a53a352b8

should we change this to run on prow instead?

**Comment by goern** [comment]
> @goern I adjusted the existing pre-commit job at [862117f](https://github.com/b4mad/racing/commit/862117fa2b272a7ebd6f86659f38ed5a53a352b8)
> 
> should we change this to run on prow instead?

Whatever fits you workflow best

**Comment by goern** [comment]
it looks like the github action is not reporting back a status in the `op1st/prow/pre-commit` context. as it is a required check, tide will not more w/o it.

**Pull request merged**
