### PR TITLE
add sentry

### PR DESCRIPTION
**Pull request by durandom**

### CODE REVIEW

**Comment by goern** [comment]
where in sentry will we find the logs?

**Comment by goern** [comment]
chk if https://github.com/b4mad/racing/pull/448/files#diff-8a19a1d5fd6104a9d9ac4400225862322272fd95510e2423f84562a27562b5f9R12 has the correct hostname :) its `mosquitto-mqtt`

**Comment by durandom** [comment]
> where in sentry will we find the logs?

what logs? I thought it captures the trace.

**Comment by goern** [comment]
logs... traces... exceptions...

/pfft ;P

**Comment by durandom** [comment]
> chk if [#448 (files)](https://github.com/b4mad/racing/pull/448/files#diff-8a19a1d5fd6104a9d9ac4400225862322272fd95510e2423f84562a27562b5f9R12) has the correct hostname :) its `mosquitto-mqtt`

Now it is.
`sops -d paddock-settings.sops.yaml | kubeseal -o yaml > paddock-settings.sealed.yaml`

Next time also give the sops some love :)

**Pull request merged**
