### PR TITLE
🔢 add a Driver and Session metrics, they are reflections of the corresponding model instance counts

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@b4mad.net>

### CODE REVIEW

**Comment by goern** [comment]
@durandom where can I find the code creating driver or session instances?

**Comment by durandom** [comment]
> @durandom where can I find the code creating driver or session instances?

only here: https://github.com/b4mad/racing/blob/0e65b1809941ca19ea96593edd79689d4d62dbf1/components/paddock/telemetry/pitcrew/session_saver.py#L39

**Pull request closed without merging**
