### PR TITLE
Tls-redirect

### PR DESCRIPTION
**Pull request by anton264**
Added tls-redirect for routes #256

### CODE REVIEW

**Comment by goern** [comment]
Hey @anton264 thanks for this PR!! :sparkles: 

I have restructured cert-manager configuration a little bit. Please have a look at https://github.com/b4mad/op1st-emea-b4mad/blob/main/manifests/organizational-unit-scope/letsencrypt-cluster-issuer.yaml#L22-L29 

I have used https://github.com/b4mad/op1st-emea-b4mad/blob/main/tests/b4mad-racing-tls-route.yaml for testing, a Cert has been created and provided as a secret. Please be aware of https://docs.openshift.com/container-platform/4.12/security/cert_manager_operator/cert-manager-operator-release-notes.html#cert-manager-operator-1.10.2-known-issues:

"Using Route objects is not fully supported. Currently, to use cert-manager Operator for Red Hat OpenShift with Routes, users must create Ingress objects, which are translated to Route objects by the Ingress-to-Route Controller. "

Would you like to go ahead and update your PR?

**Comment by anton264** [comment]
I guess all routes would have to be converted to ingress then, at least the ones with a host? 
Should be doable, but I'm a bit confused as to why https://github.com/anton264/racing/blob/main/manifests/base/paddock/route.yaml has it's host commented out? How is the traffic routed there?

**Comment by goern** [comment]
Good question. idk 🤷 Let’s create a new set ingress resources and remove all the routes

**Review by anton264 — COMMENTED** [review]
I changed one route to ingress, is that what you had in mind?

**Comment by goern** [comment]
@anton264 ja, that works for me, can you move it to `manifests/env/phobos` as that's the set of manifests getting deploys.

@durandom can you remove the `smaug` env?

**Review by anton264 — COMMENTED** [review]
Alright it has  been moved and renamed. You should probably check the current cluster config to make sure that there are no stray configs handling the paddock adress that could cause conflicts

**Comment by goern** [comment]
Thanks mate!
/lgtm
/approve

**Pull request merged**
